### ISSUE TITLE
ace-editor demo in the works?

### ISSUE THREAD

**Issue by ffd8** [yjs/yjs-demos#15]
The new [yjs.dev](https://yjs.dev/) demo is fantastic! Huge improvement over the [y-js.org](http://y-js.org/) site I saw last year. 

Any chance an ace-editor demo is in the near future pipeline? Saw it mentioned in your FOSDEM talk and hoped to find it here. Really interested in testing differences between syncing with websocket vs webRTC and the potential of offering both depending on usecase.

**Comment by dmonad** [comment]
I replied to this here https://discuss.yjs.dev/t/ace-editor-example-for-v13/68
