### ISSUE TITLE
Issue with quick insert menu in Atlaskit Editor

### ISSUE THREAD

**Issue by eshvedai** [yjs/yjs-demos#2]
Heya, I found an issue where "quick insert" menu is cropped: 

<img width="703" alt="Screen Shot 2019-08-12 at 8 31 59 pm" src="https://user-images.githubusercontent.com/26512812/62859393-5437a400-bd40-11e9-81c5-e3a938a427ff.png">

You could add a few lines of css to fix it:
```
      #editor {
        height: 100vh;
      }
```

**Comment by dmonad** [comment]
Hey, Thanks for reporting this. This is probably already fixed in a newer built of the Atlaskit editor. I'm not going to fix this because it is really hard to keep the Atlaskit editor up to date.
