### ISSUE TITLE
monaco-editor collaboration seems to be broken with y-js 13.3.0 (latest), works fine with 13.0

### ISSUE THREAD

**Issue by stefan-egorov** [yjs/yjs-demos#41]
**Describe the bug**:
When using monaco-demo with latest y-js version, user's cursors are incorrectly updated. 
![monaco-bug](https://user-images.githubusercontent.com/69171172/89229822-cbc0ac00-d5ff-11ea-87ab-7dc0fb8f4dd2.gif)
Things get really off with both typing at the same time.

**To Reproduce**

1. clone the repo. `cd monanco`
2. bump yjs to latest in `package.json` -> ~13.3.0
3. npm install
4. npm start
5. run yjs demo

**Expected behavior**
It should work similar to yjs version 13.0.0 🤔

**Environment Information**
 - Browser - Firefox 79.0 | Chrome 84.0 | Node.js v12.17.0
 - Yjs version 13.3.0

PS: The library looks really neat!

**Comment by stefan-egorov** [comment]
Hey @dmonad, to me this looks like a bug in awareness protocol. Can you confirm? Or am I missing something?

**Comment by dmonad** [comment]
Hey @stefan-egorov ,

thanks for reporting. I fixed the problem in y-monaco@0.1.0. Also see yjs/y-monaco#2
