### ISSUE TITLE
Provide README files with explanations and PoD for examples

### ISSUE THREAD

**Issue by mprinc** [yjs/yjs-demos#44]
Would be great if you could provide additional info overall for the demos but also separate README for each demo as otherwise, it is hard to explore them.

This is especially the case with similar demos like https://github.com/yjs/yjs-demos/blob/master/prosemirror and https://github.com/yjs/yjs-demos/tree/master/prosemirror-dat where you can understand the PoD only through `package.json` and even there the description property is the same (#45), so need to go to dependencies.

Surely, after some time spending "there" we can contribute PRs with it :)

**Comment by dmonad** [comment]
Hi @mprinc 

Thanks, that is very valuable feedback! I added a readme to every demo and added a brief description of what is happening.

**Comment by mprinc** [comment]
Thank you @dmonad, I looked there and all is great; clear, lot of references and understanding! Thanks again, we are "bought"! :)
