### ISSUE TITLE
Anyone working on CKEditor 5?

### ISSUE THREAD

**Issue by archonic** [yjs/yjs-demos#46]
I'm wondering if anyone has worked on a yjs solution for collaborative editing in CKEditor 5. It's supported by paid services but is extremely expensive.

**Comment by dmonad** [comment]
Hi @archonic,

no, not yet. If there are interested parties who would like to fund the development, I'd love to write a Yjs extension for CKEditor. Although we have to be aware that this would destroy their business model.
