### ISSUE TITLE
Monaco demo: Error: Unknown option '--open-page'

### ISSUE THREAD

**Issue by batchor** [yjs/yjs-demos#62]
**Checklist**

* [x ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
I couldn't run the monaco demo because of a webpack error.

**To Reproduce**
1. Go to `yjs-demos/monaco`
2. Install deps via: `npm i`
3. Run the demo `npm start` and then press yes when prompting to install webpack.

**Screenshots**
![image](https://github.com/yjs/yjs-demos/assets/128007376/8cf6117a-6af8-4045-aaae-17dec48e629f)

**Environment Information**

Output of `npx webpack version`:
```
System:
    OS: macOS 14.1.1
    CPU: (24) arm64 Apple M2 Ultra
    Memory: 797.36 MB / 64.00 GB
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 17.1
  Packages:
    css-loader: ^6.8.1 => 6.8.1 
    monaco-editor-webpack-plugin: ^7.1.0 => 7.1.0 
    style-loader: ^3.3.3 => 3.3.3
```

**Additional context**
I guess it was caused by an incompatible webpack because there is no webpack version specification in `package.json` and the latest version was instelled.

**Comment by dmonad** [comment]
Thanks for letting me know!

i forgot to push a commit. You need to `npm i` in the root directory as well. In the last commit I also updated a lot of dependencies. Can you please check it out and let me know if it fixes the problem?

**Comment by batchor** [comment]
Thanks for your prompt response.
Yes, it has been fixed and I think the issue is safe to close.
